spring.application.name=fruitshop
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.qsoxtwfuprkzabkwcdtx
spring.datasource.password=rtjoEvdpqwECYYBz
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

jwt.secret=fruitshop-super-secret-key-must-be-at-least-32-chars
jwt.expiration-ms=86400000